### ISSUE TITLE
Constructor with explicit argument

### ISSUE THREAD

**Issue by giann** [wol-soft/php-json-schema-model-generator#60]
I'd like to be able to detect missing/badly typed properties with static analysis.
So the `__construct(array $rawModelDataInput = [])` is not ideal in that regards since dev will see their error at runtime.

Would it be possible, maybe via a config option, to generate constructor of the form `__construct(string $propA, int $propB)`?

With php 8.1 we would also be able to use named arguments to avoid unreadable constructors.

**Comment by wol-soft** [comment]
Explicit arguments aren't intended by design as they would require the developer for nested objects to set up the object structure manually and pass the objects to the outer object (eg. if you have a customer and the customer has a address object you'd need to initialize the address object first).

Additionally to the manual initialization of each nested object this would disable collecting all errors from the provided data (eg. invalid address data would throw an error before invalid customer data is detected).

The intention of the objects is, to handle data from a source where you don't pass single variables to the object (eg. an API).
